# Generated by Django 5.2.11 on 2026-03-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('queja', 'Queja'), ('sugerencia', 'Sugerencia')], max_length=50)),
                ('comentario', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
            ],
        ),
    ]
