# Generated by Django 5.2.11 on 2026-04-11 13:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('general', 'Análisis General de Hábitos'), ('comparativa', 'Comparativa por Test'), ('criticas', 'Áreas Críticas de Atención')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
