# Generated by Django 5.2.11 on 2026-03-17 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', 'Reporte General de Habitos de Estudio'), ('comparativo', 'Reporte Comparativo entre Estudiantes'), ('criticas', 'Areas Criticas de Atención')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField(default=dict)),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
