# Generated by Django 5.2.11 on 2026-03-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('general', 'Análisis General de Hábitos'), ('comparativa', 'Comparativa por Test'), ('criticas', 'Áreas Críticas de Atención')], max_length=20),
        ),
    ]
