# Generated by Django 5.2.11 on 2026-04-11 13:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_seleccionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_app.opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_app.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('score_tiempo', models.FloatField(default=0)),
                ('score_metodos', models.FloatField(default=0)),
                ('score_entorno', models.FloatField(default=0)),
                ('area_debil_principal', models.CharField(max_length=20)),
                ('recomendaciones', models.JSONField(default=list)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests_app.test')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
