# Generated by Django 5.2.11 on 2026-03-17 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0004_alter_resultado_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='uuid',
        ),
    ]
