# Generated by Django 5.2.11 on 2026-03-17 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0006_resultado_uuid'),
    ]

    operations = [
    ]
