# Generated by Django 5.2.11 on 2026-03-17 04:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0007_assign_unique_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
